# This rule is not used by the project resonance itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sync.jacobtrvl.resonance resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: resonance
    app.kubernetes.io/managed-by: kustomize
  name: clustersync-viewer-role
rules:
- apiGroups:
  - sync.jacobtrvl.resonance
  resources:
  - clustersyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.jacobtrvl.resonance
  resources:
  - clustersyncs/status
  verbs:
  - get
