---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sync.jacobtrvl.resonance
  resources:
  - clustersyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.jacobtrvl.resonance
  resources:
  - clustersyncs/finalizers
  verbs:
  - update
- apiGroups:
  - sync.jacobtrvl.resonance
  resources:
  - clustersyncs/status
  verbs:
  - get
  - patch
  - update
