apiVersion: sync.jacobtrvl.resonance/v1
kind: ClusterSync
metadata:
  labels:
    app.kubernetes.io/name: resonance
    app.kubernetes.io/managed-by: kustomize
  name: clustersync-sample
spec:
  # TODO(user): Add fields here
