apiVersion: sync.io.github.jacobtrvl/v1
kind: SyncPolicy
metadata:
  labels:
    app.kubernetes.io/name: resonance
    app.kubernetes.io/managed-by: kustomize
  name: syncpolicy-sample
spec:
  # TODO(user): Add fields here
